/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_livox_demo_LivoxJNI */

#ifndef _Included_com_livox_demo_LivoxJNI
#define _Included_com_livox_demo_LivoxJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_livox_demo_LivoxJNI
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_livox_demo_LivoxJNI_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_livox_demo_LivoxJNI
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_livox_demo_LivoxJNI_start
  (JNIEnv *, jclass);

/*
 * Class:     com_livox_demo_LivoxJNI
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_livox_demo_LivoxJNI_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_livox_demo_LivoxJNI
 * Method:    setPointCloudCallback
 * Signature: (Lcom/livox/demo/PointCloudCallback;)V
 */
JNIEXPORT void JNICALL Java_com_livox_demo_LivoxJNI_setPointCloudCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
